### PR TITLE
Add Pelican Support

### LINKED ISSUE #990: Support Pelican python static site generator
Pelican is a Python static site generator
https://blog.getpelican.com/

### PR DESCRIPTION
**Pull request by askpatrickw**
Fixes #990

This is a draft, hoping the CI will run and test :-) 

- [X] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [ ] Tests are included and/or updated for code changes.
    - [x] added pelican-sample -- Generated using `pelican-quickstart`
    - [ ] platform tests
    - [ ] sample app tests
- [x] Proper license headers are included in each file. - No new files added which need licensing headers

### CODE REVIEW

**Comment by askpatrickw** [comment]
I could use a pointer to help get this over the finish line... ty!

**Comment by tonybaloney** [comment]
```

  X Microsoft.Oryx.BuildScriptGenerator.Tests.Python.PythonPlatformTests.GeneratedScript_DoesNotUseVenv [11ms]
  Error Message:
   Scriban.Syntax.ScriptRuntimeException : The variable `HasPelicanConfiguationFile` was not found
```

**Comment by arroyc** [comment]
we will look into this shortly .. thank you for contributing

**Comment by askpatrickw** [comment]
I pushed a potential fix..

**Comment by askpatrickw** [comment]
@tonybaloney can you let the CI run and tell us if it worked please?

**Comment by qianz2** [comment]
> @tonybaloney can you let the CI run and tell us if it worked please?
Just triggered the validation builds for the latest commit.

**Comment by askpatrickw** [comment]
We mere mortals cannot see the results from the CI run. ;-)

**Comment by askpatrickw** [comment]
I'm just going to close this, its not really possible for the public to contribute with out access to the CI logs.

**Pull request closed without merging**
