### PR TITLE
[From Turbo549] Correct spelling mistake in filename supportedPlatfor…

### PR DESCRIPTION
**Pull request by daniv-msft**
…mVerions.md -> supportedPlatformVersions.md

- [ ] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [ ] Tests are included and/or updated for code changes.
- [ ] Proper license headers are included in each file.

### CODE REVIEW

**Comment by daniv-msft** [comment]
As mentioned in the original PR, I have no credits for this one: @Turbo549 is the one who made the changes (https://github.com/microsoft/Oryx/pull/1496)

**Review by cormacpayne — COMMENTED** [review]
[This file](https://github.com/microsoft/Oryx/blob/main/doc/supportedRuntimeVersions.md) also contains a reference to this file and should be updated as well.

**Comment by daniv-msft** [comment]
> [This file](https://github.com/microsoft/Oryx/blob/main/doc/supportedRuntimeVersions.md) also contains a reference to this file and should be updated as well.

Thanks!

**Review by qianz2 — DISMISSED** [review]

**Review by cormacpayne — APPROVED** [review]
:shipit:

**Review by qianz2 — APPROVED** [review]

**Pull request merged**
