### PR TITLE
Update LogError messaging

### PR DESCRIPTION
**Pull request by william-msft**
- [ ] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as https://devdiv.visualstudio.com/DevDiv/_boards/board/t/Oryx/Stories/?workitem=1476021
- [ ] Tests are included and/or updated for code changes.
- [ ] Proper license headers are included in each file.

### CODE REVIEW

**Review by vijaysaayi — DISMISSED** [review]

**Comment by qianz2** [comment]
@william-msft Can we add a few tests in BuildScriptGenerator.Tests PythonBashBuildSnippetTest to verify the outputs of build snippet?

**Review by tulikac — DISMISSED** [review]

**Comment by william-msft** [comment]
> @william-msft Can we add a few tests in BuildScriptGenerator.Tests PythonBashBuildSnippetTest to verify the outputs of build snippet?

I've updated existing tests to reflect change

**Comment by qianz2** [comment]
@william, Can we make sure we have a success nightly build for it?

**Review by qianz2 — APPROVED** [review]

**Review by vijaysaayi — APPROVED** [review]

**Comment by william-msft** [comment]
> @william-msft , Can we make sure we have a success nightly build for it?

Successful nightly build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5752025&view=results

**Pull request merged**
