### PR TITLE
update dotnet core runtime image bases for openssl [ant-87 patch]

### PR DESCRIPTION
**Pull request by arroyc**
This is for patch release for ant-87 dotnetcore runtime fix for openssl

### CODE REVIEW

**Comment by qianz2** [comment]
So what is this branch `patch/20200114.13` for? Should we merge into current master branch instead

**Comment by arroyc** [comment]
> So what is this branch patch/20200114.13 for? Should we merge into current master branch instead

so this branch is made from the commit that was made for build 20200114.3, currently appservice use this build for ant87. We are sending them a patch for this ant 87, so that's the use for this branch. We should not merge it to master branch as we it is already updated.

**Comment by kichalla** [comment]
We do not want this PR anymore right?

**Comment by kichalla** [comment]
Is this PR still required?

**Pull request closed without merging**
