### PR TITLE
Correct Docker file link

### PR DESCRIPTION
**Pull request by soroshsabz**

### CODE REVIEW

**Comment by kichalla** [comment]
Thanks! @soroshsabz

**Comment by soroshsabz** [comment]
@kichalla what is meaning of `Oryx-Validation-GitHub Expected`? is any working depended on me?

**Comment by arroyc** [comment]
> @kichalla what is meaning of `Oryx-Validation-GitHub Expected`? is any working depended on me? is there any problem to merge this PR?

it's a validation build, every PR needs to have a successful validation build  before you/we can  merge it into the master branch

**Comment by qianz2** [comment]
Updated in #783

**Pull request closed without merging**
