### PR TITLE
Revert python binary changes and add dynamic installation tests

### PR DESCRIPTION
**Pull request by qianz2**
- [x] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [x] Tests are included and/or updated for code changes.
- [x] Proper license headers are included in each file.

### CODE REVIEW

**Comment by daniv-msft** [comment]
@zqian2 Looks good to me, but could you please provide more info about why we're reverting Python binary changes from https://github.com/microsoft/Oryx/pull/1302 ? Which of the issues are these creating?

**Comment by qianz2** [comment]
> @zqian2 Looks good to me, but could you please provide more info about why we're reverting Python binary changes from #1302 ? Which of the issues are these creating?

It's trying to resolve the 3.9.12 python binary issue. I looked at past PRs and found that this is the PR that make changes to python binaries and could cause the python 3.9.12 binary issue since the previous python 3.9 versions work well.
https://github.com/microsoft/Oryx/pull/1302

**Comment by daniv-msft** [comment]
> > @zqian2 Looks good to me, but could you please provide more info about why we're reverting Python binary changes from #1302 ? Which of the issues are these creating?
> 
> It's trying to resolve the 3.9.12 python binary issue. I looked at past PRs and found that this is the PR that make changes to python binaries and could cause the python 3.9.12 binary issue since the previous python 3.9 versions work well. #1302

Thanks for clarifying! And so, could you please clarify what we are losing by reverting this PR? What were we adding in @1302?

**Comment by qianz2** [comment]
> > > @zqian2 Looks good to me, but could you please provide more info about why we're reverting Python binary changes from #1302 ? Which of the issues are these creating?
> > 
> > 
> > It's trying to resolve the 3.9.12 python binary issue. I looked at past PRs and found that this is the PR that make changes to python binaries and could cause the python 3.9.12 binary issue since the previous python 3.9 versions work well. #1302
> 
> Thanks for clarifying! And so, could you please clarify what we are losing by reverting this PR? What were we adding in @1302?

It was adding a few if else statements to separately build binaries for python versions <= 3.9 (old way to build by running installPlatform.sh script) and versions >= 3.10 (build from source similarly as we do for python base image, in build/buildPythonSdkByVersion.sh script).

**Review by daniv-msft — APPROVED** [review]

**Comment by qianz2** [comment]
Closing it as we don't need to revert the previous changes.

**Comment by qianz2** [comment]
Closing it as we don't need to revert the previous changes.

**Pull request closed without merging**
