### PR TITLE
Williamhe/1435632 update sdk dotnet5 dotnet3 1 patches

### PR DESCRIPTION
**Pull request by william-msft**
- [ ] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as #1435632.
- [ ] Tests are included and/or updated for code changes.
- [ ] Proper license headers are included in each file.

### CODE REVIEW

**Review by cormacpayne — COMMENTED** [review]
Do you know if the [`versionsToBuild.txt`](https://github.com/microsoft/Oryx/blob/main/platforms/dotnet/versionsToBuild.txt) file also needs to be updated as a part of this PR, or is it something that is updated afterwards?

**Comment by william-msft** [comment]
> Do you know if the [`versionsToBuild.txt`](https://github.com/microsoft/Oryx/blob/main/platforms/dotnet/versionsToBuild.txt) file also needs to be updated as a part of this PR, or is it something that is updated afterwards?

@cormacpayne great catch! I recently added them

**Review by arroyc — APPROVED** [review]
make sure you run a successful nigthly build (atleast all the dotnetcore integration tests should be succesfull) before you merge

**Comment by william-msft** [comment]
> make sure you run a successful nigthly build (atleast all the dotnetcore integration tests should be succesfull) before you merge

Successful nightly build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5471164&view=results

**Pull request merged**
