### PR TITLE
Consolidate dependabot changes

### PR DESCRIPTION
**Pull request by cormacpayne**
~- [ ] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.~
~- [ ] Tests are included and/or updated for code changes.~
~- [ ] Proper license headers are included in each file.~

### CODE REVIEW

**Review by william-msft — DISMISSED** [review]

**Review by daniv-msft — DISMISSED** [review]
Thanks for consolidating these!

**Review by daniv-msft — DISMISSED** [review]

**Comment by daniv-msft** [comment]
@cormacpayne Thanks for updating the PR! It looks like this also caught the changes from @qianz2's Stretch removal PR.

**Comment by cormacpayne** [comment]
> @cormacpayne Thanks for updating the PR! It looks like this also caught the changes from @qianz2's Stretch removal PR.

Yep, I pulled in her changes to resolve conflicts. Once her PR is merged, I'll pull the latest from `main` into this PR and it should be good to go (pending validation CI).

**Comment by william-msft** [comment]
Noticed a `Connection reset by peer` likely due to network issue causing validation pipeline failure: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6372459&view=logs&j=d8677935-6b2c-5deb-1352-6af5877761cf&t=3b874fb6-8003-5268-cb29-197c69342b38&l=1231

I went ahead and re-ran validation pipeline

**Review by qianz2 — DISMISSED** [review]

**Review by qianz2 — APPROVED** [review]

**Review by william-msft — APPROVED** [review]

**Pull request merged**
