### PR TITLE
poetry install --no-dev

### PR DESCRIPTION
**Pull request by dimbleby**
- [ ] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [ ] Tests are included and/or updated for code changes.
- [ ] Proper license headers are included in each file.

https://github.com/microsoft/Oryx/issues/1370#issuecomment-1119314915

### CODE REVIEW

**Comment by qianz2** [comment]
Hi @dimbleby, do we have an issue related to this PR? What's the purpose of adding `--no-dev` to the `poetry install command`, could you explain it a bit? Thanks

**Comment by daniv-msft** [comment]
> Hi @dimbleby, do we have an issue related to this PR? What's the purpose of adding `--no-dev` to the `poetry install command`, could you explain it a bit? Thanks

@qianz2 Please find more details here: https://github.com/microsoft/Oryx/issues/1370
Also, adding @cormacpayne as he looked into the original issue.

**Comment by dimbleby** [comment]
specifically - as above - https://github.com/microsoft/Oryx/issues/1370#issuecomment-1119314915

I wouldn't expect that folk would want to install their dev dependencies in their deployment environment.

**Comment by daniv-msft** [comment]
@cormacpayne As you had context on the original issue, do you see an issue with adding this --no-dev parameter?

**Review by cormacpayne — APPROVED** [review]

**Comment by cormacpayne** [comment]
This change looks good to me :shipit:

**Pull request merged**
