### PR TITLE
Update to use latest version of Hugo

### PR DESCRIPTION
**Pull request by bitcrazed**
Hugo 0.76.3 is now 4 months old and lacks many fixes and improvements in more recent releases. Updating to v0.81.0 will fix several issues and unlock access to some important new features.

- [X] The purpose of this PR is explained in this message or in an issue. 
- [NA ] Tests are included and/or updated for code changes.
- [X] Proper license headers are included in each file.

### CODE REVIEW

**Comment by bitcrazed** [comment]
Also ... it'd be great if one could specify the preferred version of Hugo in an ENV VAR or similar.

**Comment by anthonychu** [comment]
@qianz2 @arroyc Could you please take a look?

**Comment by qianz2** [comment]
@bitcrazed , thanks for letting us know.. since the build couldn't be triggered for this PR, we'll send another PR for updating hugo versions soon.

**Comment by bitcrazed** [comment]
Oh, apologies - what did I do wrong with this PR?

**Comment by qianz2** [comment]
> Oh, apologies - what did I do wrong with this PR?

nothing wrong.. it's just this PR couldn't trigger the validation pipeline `Oryx-Validation-GitHub` automatically for security reasons. So I started a new one mentioning you, hope you don't mind, thanks!

**Comment by bitcrazed** [comment]
No problem. Many thanks - just wanted to make sure I knew if I did something wrong so I could avoid doing the same again next time 😜 Closing this PR.

**Pull request closed without merging**
