### PR TITLE
Updated python version to 3.11.0

### PR DESCRIPTION
**Pull request by snehapar9**
https://devdiv.visualstudio.com/DevDiv/_boards/board/t/Oryx/Stories/?workitem=1634698

### CODE REVIEW

**Comment by snehapar9** [comment]
Looks like the runtime images already support python 3.11 (Checked in contants.yaml. The runtime version circled below was already there before I made my changes)
image

Is there a way to verify we already have added support for python 3.11 in runtime images? 

I published binaries for python 3.11 to orxysdkdev -> https://oryxsdksdev.blob.core.windows.net/python?restype=container&comp=list&include=metadata

**Comment by qianz2** [comment]
> Looks like the runtime images already support python 3.11 (Checked in contants.yaml. The runtime version circled below was already there before I made my changes) image
> 
> Is there a way to verify we already have added support for python 3.11 in runtime images?
> 
> I published binaries for python 3.11 to orxysdkdev -> https://oryxsdksdev.blob.core.windows.net/python?restype=container&comp=list&include=metadata

The published python runtime images can be found here: https://mcr.microsoft.com/v2/oryx/python/tags/list
As we can see in the list, python 3.11 already supported with beta version.

**Comment by harryli0108** [comment]
> 

took a look on some prior releases and seems like the python 3.11 runtime image should be supported. Here's the link to that release: https://github.com/microsoft/Oryx/releases/tag/20220906.1

**Review by qianz2 — APPROVED** [review]

**Comment by snehapar9** [comment]
> > Looks like the runtime images already support python 3.11 (Checked in contants.yaml. The runtime version circled below was already there before I made my changes) image
> > Is there a way to verify we already have added support for python 3.11 in runtime images?
> > I published binaries for python 3.11 to orxysdkdev -> https://oryxsdksdev.blob.core.windows.net/python?restype=container&comp=list&include=metadata
> 
> The published python runtime images can be found here: https://mcr.microsoft.com/v2/oryx/python/tags/list As we can see in the list, python 3.11 already supported with beta version.

Sounds good! Thanks @qianz2 :)

**Pull request merged**
