### PR TITLE
Correct spelling mistake in filename supportedPlatformVerions.md -> supportedPlatformVersions.md

### PR DESCRIPTION
**Pull request by Turbo549**
- [x] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [x] Tests are included and/or updated for code changes.
- [x] Proper license headers are included in each file.

### CODE REVIEW

**Comment by daniv-msft** [comment]
Thank you @Turbo549 for opening this PR and fixing this typo!
Would it be possible for you to also update the two places where we references this file (with the typo in the name):
https://github.com/microsoft/Oryx/blob/main/build/tools/SharedCodeGenerator/Program.cs - Line 100
https://github.com/microsoft/Oryx/blob/main/README.md?plain=1 - Line 31

**Comment by Turbo549** [comment]
> Thank you @Turbo549 for opening this PR and fixing this typo! Would it be possible for you to also update the two places where we reference this file (with the typo in the name): https://github.com/microsoft/Oryx/blob/main/build/tools/SharedCodeGenerator/Program.cs - Line 100 https://github.com/microsoft/Oryx/blob/main/README.md?plain=1 - Line 31

Terribly sorry I missed those refs... I had searched, but that doesn't work in the forked repo.

**Review by daniv-msft — APPROVED** [review]
Looks good to me!

**Comment by daniv-msft** [comment]
> > Thank you @Turbo549 for opening this PR and fixing this typo! Would it be possible for you to also update the two places where we reference this file (with the typo in the name): https://github.com/microsoft/Oryx/blob/main/build/tools/SharedCodeGenerator/Program.cs - Line 100 https://github.com/microsoft/Oryx/blob/main/README.md?plain=1 - Line 31
> 
> Terribly sorry I missed those refs... I had searched, but that doesn't work in the forked repo.

No worries at all! Thanks again for sending a PR for this. I'll start the "Oryx-Validation" pipeline for this PR, and once it completes we'll be able to merge it. :)

**Review by qianz2 — APPROVED** [review]

**Comment by daniv-msft** [comment]
@Turbo549 FYI, I went on vacation soon after approving this PR and I didn't have a chance to merge it before leaving. Now that I'm back, I can see that multiple merge conflicts happen now due to other changes being checked in in the last couple of weeks by other team members.
Rather than asking you to spend time to resolve them, I reopened a separate PR based on the latest main version: https://github.com/microsoft/Oryx/pull/1527

Thanks again for making this change! I'm going to close this one.

**Pull request closed without merging**
