### PR TITLE
Update information for appsvc.yaml file

### PR DESCRIPTION
**Pull request by cormacpayne**
Updates the information in our `README.md` file around the `appsvc.yaml` file in accordance with the document produced previously by Jason Freeberg [here](https://github.com/JasonFreeberg/appsvc.yaml-examples).

- [x] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
~- [ ] Tests are included and/or updated for code changes.~
~- [ ] Proper license headers are included in each file.~

### CODE REVIEW

**Comment by daniv-msft** [comment]
Could you please share more context about this change? Did we receive an ask about this?
Also, if I remember correctly (cc @waliMSFT in case you remember more), we implemented some of the appsvc format, but not all of it. I might misremember though (the codebase would be more reliable than my memory :) )

**Comment by daniv-msft** [comment]
> Could you please share more context about this change? Did we receive an ask about this? Also, if I remember correctly (cc @waliMSFT in case you remember more), we implemented some of the appsvc format, but not all of it. I might misremember though (the codebase would be more reliable than my memory :) )

OK, I found the context in https://github.com/microsoft/Oryx/issues/1763. I'm still not sure that we support all the appsvc properties.

**Comment by cormacpayne** [comment]
@daniv-msft Sorry, forgot to add context pointing to the issue that was opened -- I thought we supported all four of those properties, but it looks like we don't support the `build` property (which I think is OK for the time being since we'd want to control the build command ran 99% of the time).

The `run` property was introduced by Wali as you mentioned above, and the `pre-build` and `post-build` properties have been supported in the [`DefaultBuildScriptGenerator.cs`](https://github.com/microsoft/Oryx/blob/main/src/BuildScriptGenerator/DefaultBuildScriptGenerator.cs#L337-L356) for just over a year now by [this PR](https://github.com/microsoft/Oryx/pull/1174).

Let me update the documentation to remove the snippet about the `build` property being supported.

**Review by william-msft — APPROVED** [review]

**Comment by william-msft** [comment]
I re-ran `Oryx-Validation` since there seemed to be transient errors.

**Review by daniv-msft — APPROVED** [review]

**Pull request merged**
