### PR TITLE
Developer/ericsten/php zend opcache dup

### PR DESCRIPTION
**Pull request by EricSten-MSFT**
- [x] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [ ] Tests are included and/or updated for code changes.
- [ ] Proper license headers are included in each file.

Remove duplicate zend_extension=opcache from App Service PHP images.
See https://devdiv.visualstudio.com/DevDiv/_boards/board/t/Oryx/Stories/?workitem=1554458

### CODE REVIEW

**Comment by EricSten-MSFT** [comment]
Note: Alejandro is building Oryx now, just to confirm the edits.

**Comment by william-msft** [comment]
Thanks @EricSten-MSFT! We are running our integration tests against this. Once it passes we should be good to go

**Comment by william-msft** [comment]
Integration tests: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6325600&view=results

**Comment by william-msft** [comment]
> Note: Alejandro is building Oryx now, just to confirm the edits.

Could you merge with main and push again please? There's a required change there and I'm unable to enter your branch to do it for you. Thanks!

**Comment by goalejandro** [comment]
I can confirm the _already loaded_ warning message is no longer present on the Oryx images with this PR.

**Comment by william-msft** [comment]
Merged with `main` into a new PR: https://github.com/microsoft/Oryx/pull/1452
Please refer to that. Closing this PR.

**Pull request closed without merging**
