### PR TITLE
Test clean-up: clean ShellScriptBuilder

### PR DESCRIPTION
**Pull request by kichalla**

### CODE REVIEW

**Comment by kichalla** [comment]
@arroyc Are these tests needed currently? Are they currently having the similar issue with content not present in log file because of the way NLog flushes the data?

**Comment by arroyc** [comment]
> @arroyc Are these tests needed currently? Are they currently having the similar issue with content not present in log file because of the way NLog flushes the data?

**Comment by kichalla** [comment]
@arroyc Sure, thanks for confirmation

**Comment by kichalla** [comment]
@arroyc I will add the comment in my another PR

**Pull request merged**
