### PR TITLE
disaabling colors via the envvar

### PR DESCRIPTION
**Pull request by bradygaster**
This is a fix (or at least _partial fix_) for #1456. cc @daniv-msft, with whom I've been chatting about this. Should there be any additional tweaks I'd need to make, let me know.

### CODE REVIEW

**Comment by daniv-msft** [comment]
@waliMSFT FYI, this is the PR referred to in the separate work item.

**Comment by cormacpayne** [comment]
@bradygaster @daniv-msft I'm not sure if this is user-facing from App Service, but do we know if this also affects users when building their app (_e.g._, during `dotnet publish`)? We could also set this environment variable in our build images if that's the case, but if it's only reported during runtime, then this should be good 👍

**Comment by bradygaster** [comment]
> @bradygaster @daniv-msft I'm not sure if this is user-facing from App Service, but do we know if this also affects users when building their app (_e.g._, during `dotnet publish`)? We could also set this environment variable in our build images if that's the case, but if it's only reported during runtime, then this should be good 👍

good question @cormacpayne - it shouldn't impact customers when using `dotnet publish`. This is definitely more of a "runtime" sort of issue. Folks just can't really grok their logs with all the ASCII codes.

**Comment by waliMSFT** [comment]
@bradygaster, I have tested this locally in a dotnet Image. it works fine. logs are coming without any color.

**Comment by bradygaster** [comment]
YAS! When will this ship? :)

**Review by cormacpayne — APPROVED** [review]
:shipit:

**Pull request merged**
