### PR TITLE
Add yarn2 test for vso image and sample app

### PR DESCRIPTION
**Pull request by qianz2**
- [x] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [x] Tests are included and/or updated for code changes.
- [x] Proper license headers are included in each file.

### CODE REVIEW

**Review by arroyc — CHANGES_REQUESTED** [review]
I'm bit confused ... title says add yarn2 test for vso image .. i dont see any test for vso image .. tests are for ltsversion image ... where is the sample app? Did you add a new sample app?

I thought yarn2 support is for all images .. how are you enabling it only for vso image?

**Comment by qianz2** [comment]
> I'm bit confused ... title says add yarn2 test for vso image .. i dont see any test for vso image .. tests are for ltsversion image ... where is the sample app? Did you add a new sample app?
> 
> I thought yarn2 support is for all images .. how are you enabling it only for vso image?

This support is for all images, I titled it because I referred it from a work item we had. Vso image is the place most customers consume this feature. So I have tests here using either ltsversion image or vso image, the results are same. 
Yes, I added the sample app if you can scroll down to the end of files, there has a new submodules which contains the sample yarn2 app.

**Comment by arroyc** [comment]
> > I'm bit confused ... title says add yarn2 test for vso image .. i dont see any test for vso image .. tests are for ltsversion image ... where is the sample app? Did you add a new sample app?
> > I thought yarn2 support is for all images .. how are you enabling it only for vso image?
> 
> This support is for all images, I titled it because I referred it from a work item we had. Vso image is the place most customers consume this feature. So I have tests here using either ltsversion image or vso image, the results are same.
> Yes, I added the sample app, if you can scroll down to the end of files, there has a new submodule which contains the sample yarn2 app.

alright .. it was not there earlier when I reviewed it ... i think you just pushed some changes and I can see 363  files .. so i will take a look at it.

**Review by arroyc — COMMENTED** [review]
can you delete the contents from ./yarn/cache?? Do we need them?

**Comment by qianz2** [comment]
> can you delete the contents from ./yarn/cache?? Do we need them?

Maybe we can, let me try this locally, if it works fine, I'll remove them

**Review by arroyc — APPROVED** [review]

**Pull request merged**
