### PR TITLE
Wali/migrate php7.4 image to buster 1676694

### PR DESCRIPTION
**Pull request by waliMSFT**

### CODE REVIEW

**Comment by waliMSFT** [comment]
### User Request

We had the incident  [Incident-328689550 Details - IcM (microsofticm.com)](https://portal.microsofticm.com/imp/v3/incidents/details/328689550/home) where we discovered that PHP operations which internally use Linux memory mapped operations (MMAP) on files in directories mounted by the CIFS file system driver encounter memory corruption errors. 

We are migrating apps running in Cloud Services to VMSS which uses CIFS file system driver.

 

The fix was to disable mmap and the following PRs were raised for this.

[Disable mmap for php runtime images by goalejandro · Pull Request #1366 · microsoft/Oryx (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FOryx%2Fpull%2F1366&data=05%7C01%7Cmbhuiyan%40microsoft.com%7Cbcf5526640b04cf1415808dac666e77b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638040442597495852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l%2B1Gj7F6w6ipEJKFB8UaMqKJMDAdhK4Dgk%2BF8vBQpVk%3D&reserved=0)
[Disable mmap for php-fpm by goalejandro · Pull Request #1548 · microsoft/Oryx (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FOryx%2Fpull%2F1548&data=05%7C01%7Cmbhuiyan%40microsoft.com%7Cbcf5526640b04cf1415808dac666e77b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638040442597495852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8Q842ZyL99utQAiD8yLUZ3qByeki2UXrjP%2FipZDDmZU%3D&reserved=0)
cc: @Alejandro

 

The fixes were made available with the bullseye images (oryx tags : 7.4-debian-bullseye-20221006.3 and 7.4-fpm-debian-bullseye-20221006.3) that we released earlier.

 

Currently there are two options:

Customers should migrate to bullseye images
We would need to update the PHP 7.4 buster based image with fixes.
 

We have fewer sites using bullseye based image ([Stack Updated Dashboard](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdataexplorer.azure.com%2Fdashboards%2F261b33f8-214d-482b-8884-24a4504218e5%3Fp-_startTime%3D2days%26p-_endTime%3Dnow%26p-_repository%3Dv-appsvc%252Fphp%26p-_stackVersion%3Dv-7.4%26p-_stage%3Dv-0%239b07d206-8036-4d57-8408-41f6a8d19160&data=05%7C01%7Cmbhuiyan%40microsoft.com%7Cbcf5526640b04cf1415808dac666e77b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638040442597495852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vjzs%2BDtxox9b5%2FzZ5ZFuxqds1NNiTuVsS4E92Vy%2Bu3c%3D&reserved=0)) and see that many customers would be impacted when VMSS migration happens.

 

Could you share a buster-based image with fix considering this as special circumstance ?

### PR Changes:
This PR will generate a buster image for php7.4 and php-fpm7.4. According to the requirement it should be just a onetime change.

**Comment by cormacpayne** [comment]
> Since this is a one time change to release the buster images and then switch back, I'm assuming that you will open a pull request as soon as this is merged/CI passes to revert these changes?

That was our intended plan -- get this through the CI pipeline and then immediately open a PR that reverts the change so 7.4 continues to be released as a bullseye-based image. Antares just needed a one-time buster flavor of this image.

**Comment by pauld-msft** [comment]
> That was our intended plan -- get this through the CI pipeline and then immediately open a PR that reverts the change so 7.4 continues to be released as a bullseye-based image. Antares just needed a one-time buster flavor of this image.

Sounds good. LGTM once we update the runtime base image constants to be the ones you generated and pass validation/nightly!

**Comment by waliMSFT** [comment]
> > Since this is a one time change to release the buster images and then switch back, I'm assuming that you will open a pull request as soon as this is merged/CI passes to revert these changes?
> 
> That was our intended plan -- get this through the CI pipeline and then immediately open a PR that reverts the change so 7.4 continues to be released as a bullseye-based image. Antares just needed a one-time buster flavor of this image.

I will gonna create a story and PR to revert back to bullseye image when this is done.

**Comment by pauld-msft** [comment]
> @waliMSFT there are some additional commits popping up in this PR -- would you mind pulling the latest from `main` and see if it removes the extra commits?

@cormacpayne actually, these were meant to be here. App service asked a few days ago to have the most recent version of php 7.4 to be on this buster image, since 7.4.33 will be the last version of 7.4 to be released. So I created https://github.com/microsoft/Oryx/pull/1702 to include that change in this PR, but then I seemed to have forgotten some things, hence the additional commits

**Comment by cormacpayne** [comment]
@pauld-msft OK cool, thanks for confirming -- whenever I see commits from a different user than the author, I just assume it was from a weird Git merge 😄

**Review by snehapar9 — APPROVED** [review]

**Pull request merged**
